# Generated by Django 5.2.17 on 2026-09-19 10:26

import apps.core.utils
import apps.core.validators
import apps.site_settings.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("site_name", models.CharField(default="GalPal", max_length=100)),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.utils.UploadPath("branding"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                (
                    "favicon",
                    models.ImageField(
                        blank=True,
                        help_text="PNG/JPG/WEBP",
                        null=True,
                        upload_to=apps.core.utils.UploadPath("branding"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                ("tagline", models.CharField(blank=True, max_length=200)),
                (
                    "primary_color",
                    models.CharField(
                        default="#D6336C",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                                "Enter a hex colour such as #D6336C or #FFF.",
                                code="invalid_color",
                            )
                        ],
                    ),
                ),
                (
                    "secondary_color",
                    models.CharField(
                        default="#FFF0F6",
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                                "Enter a hex colour such as #D6336C or #FFF.",
                                code="invalid_color",
                            )
                        ],
                    ),
                ),
                (
                    "accent_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                                "Enter a hex colour such as #D6336C or #FFF.",
                                code="invalid_color",
                            )
                        ],
                    ),
                ),
                (
                    "text_color",
                    models.CharField(
                        blank=True,
                        max_length=7,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^#(?:[0-9A-Fa-f]{3}|[0-9A-Fa-f]{6})$",
                                "Enter a hex colour such as #D6336C or #FFF.",
                                code="invalid_color",
                            )
                        ],
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("address", models.TextField(blank=True)),
                (
                    "whatsapp_number",
                    models.CharField(
                        blank=True,
                        help_text="Digits only with country code, e.g. 8801712345678",
                        max_length=20,
                    ),
                ),
                (
                    "support_hours",
                    models.CharField(
                        blank=True, help_text="e.g. Sat-Thu, 10am-8pm", max_length=200
                    ),
                ),
                (
                    "facebook_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="Facebook page URL", max_length=300
                    ),
                ),
                (
                    "instagram_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="Instagram page URL", max_length=300
                    ),
                ),
                (
                    "youtube_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="YouTube page URL", max_length=300
                    ),
                ),
                (
                    "tiktok_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="TikTok page URL", max_length=300
                    ),
                ),
                (
                    "x_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="X (Twitter) page URL", max_length=300
                    ),
                ),
                (
                    "linkedin_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="LinkedIn page URL", max_length=300
                    ),
                ),
                (
                    "pinterest_url",
                    apps.site_settings.models.HttpURLField(
                        blank=True, help_text="Pinterest page URL", max_length=300
                    ),
                ),
                (
                    "meta_pixel_id",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^\\d{8,20}$",
                                "A Meta Pixel ID is 8-20 digits.",
                                code="invalid_pixel_id",
                            )
                        ],
                    ),
                ),
                (
                    "meta_capi_access_token",
                    models.CharField(
                        blank=True,
                        help_text="SECRET: Meta Conversions API token",
                        max_length=500,
                    ),
                ),
                (
                    "meta_capi_test_event_code",
                    models.CharField(
                        blank=True, help_text="Server-only", max_length=50
                    ),
                ),
                (
                    "ga4_measurement_id",
                    models.CharField(
                        blank=True,
                        max_length=22,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^G-[A-Z0-9]{4,20}$",
                                "A GA4 measurement ID looks like G-XXXXXXXXXX.",
                                code="invalid_ga4_id",
                            )
                        ],
                    ),
                ),
                (
                    "ga4_api_secret",
                    models.CharField(
                        blank=True,
                        help_text="SECRET: GA4 Measurement Protocol API secret",
                        max_length=200,
                    ),
                ),
                (
                    "gtm_id",
                    models.CharField(
                        blank=True,
                        max_length=14,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^GTM-[A-Z0-9]{4,12}$",
                                "A GTM container ID looks like GTM-XXXXXXX.",
                                code="invalid_gtm_id",
                            )
                        ],
                    ),
                ),
                (
                    "tiktok_pixel_id",
                    models.CharField(
                        blank=True,
                        max_length=32,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9]{8,32}$",
                                "A TikTok pixel ID is 8-32 letters/digits.",
                                code="invalid_tiktok_pixel_id",
                            )
                        ],
                    ),
                ),
                (
                    "custom_header_script",
                    models.TextField(
                        blank=True,
                        help_text="Injected into <head> by the storefront",
                        max_length=20000,
                    ),
                ),
                (
                    "custom_footer_script",
                    models.TextField(
                        blank=True,
                        help_text="Injected before </body> by the storefront",
                        max_length=20000,
                    ),
                ),
                ("send_manual_orders_to_capi", models.BooleanField(default=False)),
                (
                    "currency_code",
                    models.CharField(
                        default="BDT",
                        max_length=3,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Z]{3}$", "Use a 3-letter ISO code, e.g. BDT."
                            )
                        ],
                    ),
                ),
                ("currency_symbol", models.CharField(default="৳", max_length=5)),
                (
                    "tax_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="VAT/tax % added to orders. Blank or 0 = no tax.",
                        max_digits=5,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Subtotal at which shipping becomes free. Blank or 0 = disabled. A delivery zone can override it.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("guest_checkout_enabled", models.BooleanField(default=True)),
                (
                    "allow_checkout_account_creation",
                    models.BooleanField(
                        default=True,
                        help_text='Allow "save my details" account creation at guest checkout',
                    ),
                ),
                ("low_stock_threshold", models.PositiveIntegerField(default=5)),
                ("maintenance_mode", models.BooleanField(default=False)),
                ("default_meta_title", models.CharField(blank=True, max_length=70)),
                (
                    "default_meta_description",
                    models.CharField(blank=True, max_length=320),
                ),
                (
                    "default_og_image",
                    models.ImageField(
                        blank=True,
                        help_text="Default social-share image",
                        null=True,
                        upload_to=apps.core.utils.UploadPath("branding"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        editable=False,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "site settings",
                "verbose_name_plural": "site settings",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)), name="site_settings_single_row"
                    )
                ],
            },
        ),
    ]
