# Generated by Django 5.2.17 on 2026-09-28 07:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_settings', '0002_default_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_barcode_height',
            field=models.DecimalField(decimal_places=1, default=16, help_text='Invoice print: barcode height (12–24 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(12), django.core.validators.MaxValueValidator(24)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_content_width',
            field=models.DecimalField(decimal_places=1, default=100, help_text='Invoice print: content width (70–100 %)', max_digits=4, validators=[django.core.validators.MinValueValidator(70), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_logo_width',
            field=models.DecimalField(decimal_places=1, default=58, help_text='Invoice print: logo width (30–80 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(80)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_padding_bottom',
            field=models.DecimalField(decimal_places=1, default=9, help_text='Invoice print: bottom padding (0–25 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_padding_left',
            field=models.DecimalField(decimal_places=1, default=9, help_text='Invoice print: left padding (0–25 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_padding_right',
            field=models.DecimalField(decimal_places=1, default=9, help_text='Invoice print: right padding (0–25 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_padding_top',
            field=models.DecimalField(decimal_places=1, default=9, help_text='Invoice print: top padding (0–25 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(25)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_qr_size',
            field=models.DecimalField(decimal_places=1, default=28, help_text='Invoice print: QR code size (20–40 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(20), django.core.validators.MaxValueValidator(40)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_section_spacing',
            field=models.DecimalField(decimal_places=1, default=4, help_text='Invoice print: section spacing (1–10 mm)', max_digits=4, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='invoice_text_size',
            field=models.DecimalField(decimal_places=1, default=9, help_text='Invoice print: text size (8–12 pt)', max_digits=4, validators=[django.core.validators.MinValueValidator(8), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
