/* eslint-disable @next/next/no-img-element -- the logo is printed; a plain <img> keeps it in the print layout */
import { layoutStyle } from "@/lib/invoiceLayout";
import ParcelCodes from "./ParcelCodes";

// The ONE invoice layout (A4 portrait), used for every role and every page that shows an invoice. Pure: it renders
// the view model from lib/invoice.js#toInvoiceView and nothing else. Printing hides everything on the page except
// `.invoice-sheet` (see the invoice print rules in globals.css).
//
// The parcel QR code and barcode (ParcelCodes) are vector SVG generated by the backend from the order's saved Parcel
// ID; no third-party code service ever sees it.
//
// Print layout: `invoice.layout` (the saved Invoice Print Settings, or a live draft on the settings page) becomes CSS
// custom properties on the sheet (lib/invoiceLayout.js); the stylesheet derives every size from them.
// `a4` — always render at the real 210mm width (the settings page's scaled preview), never the phone layout.
export default function InvoiceTemplate({ invoice, a4 = false }) {
  const { store, billTo, payment, items, totals, parcel } = invoice;

  return (
    <article
      className={`invoice-sheet${a4 ? " invoice-sheet--a4" : ""}`}
      style={layoutStyle(invoice.layout)}
      aria-label={`Invoice ${invoice.invoiceNumber}`}
    >
      <div className="invoice-content">
        <header className="invoice-header">
          <div className="invoice-store">
            {/* The GalPal logo, the exact file the site footer/dashboard show (its wordmark is the store name). */}
            <img src="/assets/galpal/galpal-logo.svg" alt={store.name || "GalPal"} width={1012} height={196} className="invoice-logo" />
            {store.lines.map((line) => (
              <p key={line} className="invoice-muted">{line}</p>
            ))}
          </div>
          <div className="invoice-meta">
            <h1 className="invoice-title">INVOICE</h1>
            <dl>
              <div><dt>Invoice #</dt><dd>{invoice.invoiceNumber}</dd></div>
              <div><dt>Order #</dt><dd>{invoice.orderNumber}</dd></div>
              <div><dt>Date</dt><dd>{invoice.date}</dd></div>
              <div><dt>Time</dt><dd>{invoice.time}</dd></div>
            </dl>
          </div>
        </header>

        <section className="invoice-parties">
          <div>
            <p className="invoice-label">Bill To</p>
            <p className="invoice-strong">{billTo.name}</p>
            {billTo.lines.map((line) => (
              <p key={line}>{line}</p>
            ))}
          </div>
          <div className="invoice-parties__payment">
            <p className="invoice-label">Payment</p>
            <p className="invoice-strong">{payment.method}</p>
            <p>Status: {payment.status}</p>
          </div>
        </section>

        <table className="invoice-items">
          <thead>
            <tr>
              <th scope="col">Product</th>
              <th scope="col" className="invoice-num">Qty</th>
              <th scope="col" className="invoice-num">Price</th>
              <th scope="col" className="invoice-num">Discount</th>
              <th scope="col" className="invoice-num">Total</th>
            </tr>
          </thead>
          <tbody>
            {items.map((item) => (
              <tr key={item.key}>
                <td data-label="Product">
                  <span className="invoice-strong">{item.name}</span>
                  {item.meta && <span className="invoice-muted invoice-block">{item.meta}</span>}
                </td>
                <td data-label="Qty" className="invoice-num">{item.quantity}</td>
                <td data-label="Price" className="invoice-num">{item.price}</td>
                <td data-label="Discount" className="invoice-num">{item.discount}</td>
                <td data-label="Total" className="invoice-num invoice-strong">{item.total}</td>
              </tr>
            ))}
          </tbody>
        </table>

        <div className="invoice-summary">
          <dl>
            {totals.map((row) => (
              <div key={row.label}><dt>{row.label}</dt><dd>{row.value}</dd></div>
            ))}
            <div className="invoice-summary__total"><dt>Total</dt><dd>{invoice.grandTotal}</dd></div>
            <div><dt>Paid</dt><dd>{invoice.paid}</dd></div>
            <div className="invoice-summary__due"><dt>Due</dt><dd>{invoice.due}</dd></div>
          </dl>
        </div>

        <section className="invoice-parcel">
          <div>
            <p className="invoice-label">Parcel ID</p>
            {parcel ? (
              <>
                <p className="invoice-parcel__id">{parcel.id}</p>
                {parcel.courier && <p className="invoice-muted">{parcel.courier}</p>}
              </>
            ) : (
              <p className="invoice-muted">Not assigned yet — it appears here once the order is handed to the courier.</p>
            )}
          </div>
          {parcel && <ParcelCodes id={parcel.id} qrSvg={parcel.qrSvg} barcodeSvg={parcel.barcodeSvg} />}
        </section>

        {invoice.note && (
          <p className="invoice-note"><span className="invoice-label">Note</span> {invoice.note}</p>
        )}

        <footer className="invoice-footer">Thank you for your purchase.</footer>
      </div>
    </article>
  );
}
