# Generated by Django 5.2.17 on 2026-10-03 05:18

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_stock_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=120)),
                ('kind', models.CharField(choices=[('percentage', 'Percentage'), ('fixed', 'Fixed amount')], max_length=10)),
                ('value', models.DecimalField(decimal_places=2, help_text='Percent (0–100] or taka off, depending on `kind`.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('target_type', models.CharField(choices=[('category', 'Category'), ('products', 'Specific products')], max_length=10)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(db_index=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Off = never applies, whatever the dates.')),
                ('category', models.ForeignKey(blank=True, help_text='Category target: this category and every sub-category below it.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discounts', to='catalog.category')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('products', models.ManyToManyField(blank=True, related_name='discounts', to='catalog.product')),
            ],
            options={
                'ordering': ['-starts_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('ends_at__gt', models.F('starts_at'))), name='discount_ends_after_start'), models.CheckConstraint(condition=models.Q(('value__gt', 0)), name='discount_value_positive'), models.CheckConstraint(condition=models.Q(models.Q(('kind', 'percentage'), _negated=True), ('value__lte', 100), _connector='OR'), name='discount_percentage_lte_100')],
            },
        ),
    ]
