import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/shared/Navbar";
import Footer from "@/component/shared/Footer";
import FooterGate from "@/component/shared/FooterGate";
import AppToaster from "@/component/shared/AppToaster";
import { CartProvider } from "@/component/cart/CartProvider";
import CartDrawer from "@/component/cart/CartDrawer";
import { getCurrencySymbol } from "@/lib/siteSettings";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const currencySymbol = await getCurrencySymbol();
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col" suppressHydrationWarning>
        <CartProvider currencySymbol={currencySymbol}>
          <Navbar />
          {children}
          <FooterGate>
            <Footer />
          </FooterGate>
          <CartDrawer />
        </CartProvider>
        <AppToaster />
      </body>
    </html>
  );
}
