# Generated by Django 5.2.17 on 2026-09-20 05:46

import apps.core.utils
import apps.core.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroBanner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "title",
                    models.CharField(
                        help_text="Internal label, not shown to customers.",
                        max_length=120,
                    ),
                ),
                (
                    "desktop_image",
                    models.ImageField(
                        upload_to=apps.core.utils.UploadPath("banners"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                (
                    "tablet_image",
                    models.ImageField(
                        blank=True,
                        help_text="Falls back to the desktop image when blank.",
                        null=True,
                        upload_to=apps.core.utils.UploadPath("banners"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                (
                    "mobile_image",
                    models.ImageField(
                        blank=True,
                        help_text="Falls back to the desktop image when blank.",
                        null=True,
                        upload_to=apps.core.utils.UploadPath("banners"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                (
                    "link_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[apps.core.validators.validate_http_url],
                    ),
                ),
                (
                    "link_target",
                    models.CharField(
                        choices=[("_self", "Same tab"), ("_blank", "New tab")],
                        default="_self",
                        max_length=7,
                    ),
                ),
                ("button_text", models.CharField(blank=True, max_length=40)),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, help_text="Blank: visible immediately.", null=True
                    ),
                ),
                (
                    "end_at",
                    models.DateTimeField(
                        blank=True, help_text="Blank: never expires.", null=True
                    ),
                ),
                (
                    "slide_delay_override",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Seconds. Blank uses the slider-wide default.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["is_active", "sort_order"],
                        name="banners_her_is_acti_0898c0_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("end_at__isnull", True),
                            ("start_at__isnull", True),
                            ("end_at__gt", models.F("start_at")),
                            _connector="OR",
                        ),
                        name="hero_banner_end_after_start",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="HeroSliderConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "slide_delay_seconds",
                    models.PositiveIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(120),
                        ],
                    ),
                ),
                ("autoplay", models.BooleanField(default=True)),
                ("loop", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "hero slider config",
                "verbose_name_plural": "hero slider config",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("id", 1)),
                        name="hero_slider_config_single_row",
                    )
                ],
            },
        ),
    ]
