# Generated by Django 5.2.17 on 2026-10-01 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orders', '0002_invoice_layout_overrides'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('order_placed', 'Order placed'), ('order_status_changed', 'Order status changed'), ('password_reset_otp', 'Password reset code'), ('new_account', 'New account details'), ('low_stock', 'Low stock alert (to admins)'), ('review_reply', 'Reply to a review'), ('back_in_stock', 'Back in stock (Notify Me)')], db_index=True, max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], db_index=True, max_length=5)),
                ('recipient', models.CharField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('body', models.TextField(help_text='As sent, except secrets (codes, passwords), which are masked.')),
                ('has_secret', models.BooleanField(default=False, help_text="The real message held a secret, so it can't be re-sent from the log.")),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('retrying', 'Retrying'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='queued', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error', models.CharField(blank=True, max_length=500)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to='orders.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.CharField(choices=[('order_placed', 'Order placed'), ('order_status_changed', 'Order status changed'), ('password_reset_otp', 'Password reset code'), ('new_account', 'New account details'), ('low_stock', 'Low stock alert (to admins)'), ('review_reply', 'Reply to a review'), ('back_in_stock', 'Back in stock (Notify Me)')], max_length=30)),
                ('channel', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS')], max_length=5)),
                ('subject', models.CharField(blank=True, help_text='Email only.', max_length=200)),
                ('body', models.TextField(max_length=5000)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['event', 'channel'],
                'constraints': [models.UniqueConstraint(fields=('event', 'channel'), name='notification_template_unique_event_channel')],
            },
        ),
    ]
