# Generated by Django 5.2.17 on 2026-09-20 10:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("coupons", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="cart",
            name="coupon",
            field=models.ForeignKey(
                blank=True,
                help_text="Applied via apps.coupons.services.apply_coupon_to_cart; discount is computed live, never stored.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="coupons.coupon",
            ),
        ),
    ]
