# Generated by Django 5.2.17 on 2026-10-04 10:36

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

# The sections the homepage hardcoded before this was configurable: (category slug, position, sort order).
INITIAL = [("makeup", "before_video", 0), ("skincare", "before_video", 1), ("acsosories", "after_video", 0)]


def seed(apps, schema_editor):
    Category = apps.get_model("catalog", "Category")
    Section = apps.get_model("content", "HomepageCategorySection")
    if Section.objects.exists():
        return
    for slug, position, order in INITIAL:
        category = Category.objects.filter(slug=slug).first()
        if category is not None:  # a category that doesn't exist here is simply skipped
            Section.objects.create(category=category, position=position, sort_order=order, product_limit=8, rows=1)


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stock_notification'),
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageCategorySection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('position', models.CharField(choices=[('before_video', 'Before the skincare video'), ('after_video', 'After the skincare video')], default='before_video', max_length=12)),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Lower first, within its position.')),
                ('product_limit', models.PositiveSmallIntegerField(default=8, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(48)])),
                ('rows', models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sections', to='catalog.category')),
            ],
            options={
                'ordering': ['position', 'sort_order', 'id'],
            },
        ),
        migrations.RunPython(seed, migrations.RunPython.noop),
    ]
