# Generated by Django 5.2.17 on 2026-10-10 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_stock_notification'),
        ('content', '0002_homepage_category_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagecategorysection',
            name='source',
            field=models.CharField(choices=[('category', 'Category'), ('featured', 'Trending (Is Featured)'), ('new_arrival', 'New Arrivals (Is New Arrival)'), ('bestseller', 'Bestsellers (Is Bestseller)')], db_index=True, default='category', max_length=12),
        ),
        migrations.AddField(
            model_name='homepagecategorysection',
            name='title',
            field=models.CharField(blank=True, help_text='Flag sections only; category sections use the category name.', max_length=80),
        ),
        migrations.AlterField(
            model_name='homepagecategorysection',
            name='category',
            field=models.ForeignKey(blank=True, help_text='Category sections only.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='homepage_sections', to='catalog.category'),
        ),
    ]
