# Generated by Django 5.2.17 on 2026-09-20 05:57

import apps.core.utils
import apps.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_product_productattribute_attributevalue_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="VideoCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("title", models.CharField(max_length=120)),
                (
                    "video_file",
                    models.FileField(
                        blank=True,
                        upload_to=apps.core.utils.UploadPath("videos"),
                        validators=[apps.core.validators.validate_video_file],
                    ),
                ),
                (
                    "external_url",
                    models.URLField(
                        blank=True,
                        max_length=500,
                        validators=[apps.core.validators.validate_http_url],
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        upload_to=apps.core.utils.UploadPath("videos"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                ("sort_order", models.PositiveIntegerField(db_index=True, default=0)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="videos", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("video_file", ""),
                                models.Q(("external_url", ""), _negated=True),
                            ),
                            models.Q(
                                models.Q(("video_file", ""), _negated=True),
                                ("external_url", ""),
                            ),
                            _connector="OR",
                        ),
                        name="video_card_exactly_one_source",
                    )
                ],
            },
        ),
    ]
