# Generated by Django 5.2.17 on 2026-09-21 06:48

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_product_productattribute_attributevalue_and_more"),
        ("coupons", "0001_initial"),
        ("shipping", "0002_seed_defaults"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "number",
                    models.CharField(
                        help_text="Human-readable and not guessable, e.g. GP-260921-7K3F",
                        max_length=20,
                        unique=True,
                    ),
                ),
                ("customer_name", models.CharField(max_length=150)),
                ("phone", models.CharField(db_index=True, max_length=11)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("division", models.CharField(blank=True, max_length=60)),
                ("district", models.CharField(max_length=60)),
                ("area", models.CharField(blank=True, max_length=100)),
                ("address_line", models.CharField(max_length=255)),
                ("postal_code", models.CharField(blank=True, max_length=10)),
                (
                    "note",
                    models.TextField(
                        blank=True, help_text="The customer's note for delivery"
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("website", "Website"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("tiktok", "TikTok"),
                            ("whatsapp", "WhatsApp"),
                            ("messenger", "Messenger"),
                            ("call", "Phone call"),
                            ("other", "Other"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("source_note", models.CharField(blank=True, max_length=255)),
                ("is_manual", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("cod", "Cash on delivery"),
                            ("online", "Online payment"),
                        ],
                        default="cod",
                        max_length=10,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("unpaid", "Unpaid"),
                            ("paid", "Paid"),
                            ("partially_paid", "Partially paid"),
                            ("refunded", "Refunded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="unpaid",
                        max_length=15,
                    ),
                ),
                (
                    "subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("coupon_code", models.CharField(blank=True, max_length=32)),
                ("shipping_zone_name", models.CharField(blank=True, max_length=80)),
                ("delivery_method_name", models.CharField(blank=True, max_length=60)),
                (
                    "shipping_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("shipping_free_reason", models.CharField(blank=True, max_length=30)),
                ("shipping_overridden", models.BooleanField(default=False)),
                (
                    "shipping_override_reason",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "tax_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "tax_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "grand_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("courier_name", models.CharField(blank=True, max_length=60)),
                ("tracking_id", models.CharField(blank=True, max_length=100)),
                ("consignment_id", models.CharField(blank=True, max_length=100)),
                (
                    "stock_released_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Set once the order's stock has been put back.",
                        null=True,
                    ),
                ),
                (
                    "fingerprint",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="Hash of phone + items, for duplicate detection.",
                        max_length=64,
                    ),
                ),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "delivery_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="shipping.deliverymethod",
                    ),
                ),
                (
                    "shipping_zone",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="orders",
                        to="shipping.deliveryzone",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="OrderItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("product_name", models.CharField(max_length=200)),
                ("sku", models.CharField(max_length=64)),
                (
                    "variant_label",
                    models.CharField(
                        blank=True,
                        help_text='e.g. "Shade: Rose / Size: 50ml"',
                        max_length=200,
                    ),
                ),
                (
                    "image",
                    models.CharField(
                        blank=True,
                        help_text="Storage path of the image at order time",
                        max_length=500,
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "line_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "stock_deducted",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Units actually taken from stock (0 if stock isn't managed).",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="orders.order",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.product",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_items",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="OrderNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField(max_length=2000)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notes",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="OrderStatusHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("from_status", models.CharField(blank=True, max_length=12)),
                (
                    "to_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("confirmed", "Confirmed"),
                            ("processing", "Processing"),
                            ("shipped", "Shipped"),
                            ("delivered", "Delivered"),
                            ("cancelled", "Cancelled"),
                            ("returned", "Returned"),
                            ("failed", "Failed"),
                        ],
                        max_length=12,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=500)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="orders.order",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "order status history",
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["status", "-created_at"], name="orders_orde_status_079368_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["source", "-created_at"], name="orders_orde_source_bb9690_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["customer", "-created_at"],
                name="orders_orde_custome_413d7d_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("subtotal__gte", 0)), name="order_subtotal_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="order_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__lte", models.F("subtotal"))),
                name="order_discount_lte_subtotal",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("shipping_charge__gte", 0)),
                name="order_shipping_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("tax_amount__gte", 0)), name="order_tax_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="order",
            constraint=models.CheckConstraint(
                condition=models.Q(("grand_total__gte", 0)),
                name="order_grand_total_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)),
                name="order_item_quantity_gte_1",
            ),
        ),
    ]
