# Generated by Django 5.2.17 on 2026-09-28 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice_layout',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
