# Generated by Django 5.2.17 on 2026-10-01 10:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor_name', models.CharField(blank=True, help_text='Kept if the account is later deleted.', max_length=150)),
                ('actor_role', models.CharField(blank=True, max_length=10)),
                ('action', models.CharField(db_index=True, max_length=60)),
                ('target_type', models.CharField(blank=True, db_index=True, max_length=40)),
                ('target_id', models.CharField(blank=True, db_index=True, max_length=40)),
                ('target_label', models.CharField(blank=True, max_length=200)),
                ('changes', models.JSONField(blank=True, default=dict, help_text='{"field": [before, after]}')),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('method', models.CharField(blank=True, max_length=7)),
                ('path', models.CharField(blank=True, max_length=300)),
                ('status_code', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['target_type', 'target_id'], name='audit_audit_target__2d648a_idx')],
            },
        ),
    ]
