# Generated by Django 5.2.17 on 2026-09-20 04:33

import apps.core.utils
import apps.core.validators
import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("slug_is_custom", models.BooleanField(default=False, editable=False)),
                ("is_deleted", models.BooleanField(db_index=True, default=False)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("name", models.CharField(max_length=200)),
                ("short_description", models.CharField(blank=True, max_length=300)),
                (
                    "full_description",
                    models.TextField(blank=True, help_text="Rich text/HTML"),
                ),
                (
                    "user_guide",
                    models.TextField(
                        blank=True, help_text="How to use, rich text/HTML"
                    ),
                ),
                (
                    "feature_image",
                    models.ImageField(
                        upload_to=apps.core.utils.UploadPath("products"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                (
                    "regular_price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("sale_start_at", models.DateTimeField(blank=True, null=True)),
                ("sale_end_at", models.DateTimeField(blank=True, null=True)),
                ("sku", models.CharField(max_length=64, unique=True)),
                ("barcode", models.CharField(blank=True, max_length=64)),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("manage_stock", models.BooleanField(default=True)),
                (
                    "low_stock_threshold",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Blank uses the site-wide default from Site Settings.",
                        null=True,
                    ),
                ),
                (
                    "stock_status",
                    models.CharField(
                        choices=[
                            ("in_stock", "In stock"),
                            ("out_of_stock", "Out of stock"),
                            ("backorder", "Backorder"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=15,
                    ),
                ),
                ("has_variants", models.BooleanField(default=False)),
                (
                    "skin_type",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(
                            choices=[
                                ("oily", "Oily"),
                                ("dry", "Dry"),
                                ("combination", "Combination"),
                                ("normal", "Normal"),
                                ("sensitive", "Sensitive"),
                                ("all", "All skin types"),
                            ],
                            max_length=15,
                        ),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
                (
                    "key_ingredients",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Short highlight list",
                        size=None,
                    ),
                ),
                (
                    "ingredients",
                    models.TextField(
                        blank=True, help_text="Full ingredient list (INCI)"
                    ),
                ),
                (
                    "size_value",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "size_unit",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ml", "ml"),
                            ("l", "L"),
                            ("g", "g"),
                            ("kg", "kg"),
                            ("pcs", "pcs"),
                            ("oz", "oz"),
                        ],
                        max_length=5,
                    ),
                ),
                ("country_of_origin", models.CharField(blank=True, max_length=80)),
                ("manufacture_date", models.DateField(blank=True, null=True)),
                (
                    "expiry_date",
                    models.DateField(
                        blank=True,
                        help_text="Expiry date / shelf life (PAO)",
                        null=True,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("unisex", "Unisex"),
                            ("women", "Women"),
                            ("men", "Men"),
                            ("kids", "Kids"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_featured", models.BooleanField(db_index=True, default=False)),
                ("is_new_arrival", models.BooleanField(db_index=True, default=False)),
                ("is_bestseller", models.BooleanField(db_index=True, default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("meta_title", models.CharField(blank=True, max_length=70)),
                ("meta_description", models.CharField(blank=True, max_length=320)),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.utils.UploadPath("products"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                (
                    "average_rating",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=3
                    ),
                ),
                ("review_count", models.PositiveIntegerField(default=0)),
                (
                    "brand",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="products",
                        to="catalog.brand",
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="products", to="catalog.tag"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductAttribute",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("slug_is_custom", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=60)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="product_attribute_unique_name",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttributeValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("slug_is_custom", models.BooleanField(default=False, editable=False)),
                ("value", models.CharField(max_length=60)),
                (
                    "attribute",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="values",
                        to="catalog.productattribute",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "attribute values",
                "ordering": ["value"],
            },
        ),
        migrations.CreateModel(
            name="ProductCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_links",
                        to="catalog.category",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="category_links",
                        to="catalog.product",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="product",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="products",
                through="catalog.ProductCategory",
                to="catalog.category",
            ),
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "image",
                    models.ImageField(
                        upload_to=apps.core.utils.UploadPath("products"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                ("alt_text", models.CharField(blank=True, max_length=150)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "option_signature",
                    models.CharField(default="", editable=False, max_length=255),
                ),
                ("sku", models.CharField(max_length=64, unique=True)),
                (
                    "regular_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                ("stock_quantity", models.PositiveIntegerField(default=0)),
                ("manage_stock", models.BooleanField(default=True)),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=apps.core.utils.UploadPath("products"),
                        validators=[apps.core.validators.validate_image_file],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "attribute_values",
                    models.ManyToManyField(
                        blank=True, related_name="variants", to="catalog.attributevalue"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity_change", models.IntegerField()),
                ("balance_after", models.PositiveIntegerField()),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("return", "Return"),
                            ("manual", "Manual adjustment"),
                            ("restock", "Restock"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "reference",
                    models.CharField(
                        blank=True, help_text="e.g. an order number", max_length=100
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=255)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="attributevalue",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("value"),
                models.F("attribute"),
                name="attribute_value_unique_per_attribute",
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                fields=("product", "category"), name="product_category_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="productcategory",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("product",),
                name="product_one_primary_category",
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["status", "-created_at"], name="catalog_pro_status_c865a0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["brand", "status"], name="catalog_pro_brand_i_f60d77_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("regular_price__gt", 0)),
                name="product_regular_price_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_price__isnull", True),
                    ("discount_price__lt", models.F("regular_price")),
                    _connector="OR",
                ),
                name="product_discount_price_lower",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.UniqueConstraint(
                fields=("product", "option_signature"),
                name="variant_unique_option_combo",
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_price__isnull", True),
                    ("regular_price__isnull", True),
                    ("discount_price__lt", models.F("regular_price")),
                    _connector="OR",
                ),
                name="variant_discount_price_lower",
            ),
        ),
        migrations.AddIndex(
            model_name="stockmovement",
            index=models.Index(
                fields=["product", "-created_at"], name="catalog_sto_product_c898c4_idx"
            ),
        ),
    ]
