# Generated by Django 5.2.17 on 2026-09-21 06:19

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryZone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("slug_is_custom", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=80)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        help_text="Shown to the Admin only, e.g. how the zone is matched.",
                        max_length=255,
                    ),
                ),
                (
                    "charge",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_days_max",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "estimated_days_label",
                    models.CharField(
                        blank=True,
                        help_text='Overrides the generated text, e.g. "Same day" or "1-2 days".',
                        max_length=50,
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Blank: use the global threshold from Site Settings. 0: never free. Otherwise the subtotal that makes shipping free here.",
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "is_default",
                    models.BooleanField(
                        default=False,
                        help_text="The fallback zone for addresses no other zone covers.",
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
                ("slug", models.SlugField(max_length=80, unique=True)),
                ("division", models.CharField(db_index=True, max_length=40)),
                (
                    "aliases",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=60),
                        blank=True,
                        default=list,
                        size=None,
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="DeliveryMethod",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("slug_is_custom", models.BooleanField(default=False, editable=False)),
                ("name", models.CharField(max_length=60)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "extra_charge",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "estimated_days_label",
                    models.CharField(
                        blank=True,
                        help_text='Overrides the zone estimate when this method is chosen, e.g. "Next day".',
                        max_length=50,
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=False)),
                ("sort_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sort_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        django.db.models.functions.text.Lower("name"),
                        name="shipping_method_name_ci_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("extra_charge__gte", 0)),
                        name="shipping_method_extra_gte_0",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingChargeHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("zone_name", models.CharField(max_length=80)),
                (
                    "old_charge",
                    models.DecimalField(decimal_places=2, max_digits=10, null=True),
                ),
                ("new_charge", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "changed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charge_history",
                        to="shipping.deliveryzone",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "shipping charge history",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="ZoneDistrict",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "areas",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=models.CharField(max_length=100),
                        blank=True,
                        default=list,
                        help_text="Empty: the whole district.",
                        size=None,
                    ),
                ),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_links",
                        to="shipping.district",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coverage",
                        to="shipping.deliveryzone",
                    ),
                ),
            ],
            options={
                "ordering": ["district__name"],
            },
        ),
        migrations.AddField(
            model_name="deliveryzone",
            name="districts",
            field=models.ManyToManyField(
                blank=True,
                related_name="zones",
                through="shipping.ZoneDistrict",
                to="shipping.district",
            ),
        ),
        migrations.AddConstraint(
            model_name="zonedistrict",
            constraint=models.UniqueConstraint(
                fields=("zone", "district"), name="shipping_zone_district_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="zonedistrict",
            constraint=models.UniqueConstraint(
                condition=models.Q(("areas", [])),
                fields=("district",),
                name="shipping_one_whole_district_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="shipping_zone_name_ci_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(("charge__gte", 0)),
                name="shipping_zone_charge_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("free_shipping_threshold__isnull", True),
                    ("free_shipping_threshold__gte", 0),
                    _connector="OR",
                ),
                name="shipping_zone_threshold_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("estimated_days_min__isnull", True),
                    ("estimated_days_max__isnull", True),
                    ("estimated_days_min__lte", models.F("estimated_days_max")),
                    _connector="OR",
                ),
                name="shipping_zone_days_min_lte_max",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="shipping_one_default_zone",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryzone",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("is_default", False), ("is_active", True), _connector="OR"
                ),
                name="shipping_default_zone_active",
            ),
        ),
    ]
