# Generated by Django 5.2.17 on 2026-09-22 06:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackingEventLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_name",
                    models.CharField(
                        choices=[
                            ("PageView", "PageView"),
                            ("ViewContent", "ViewContent"),
                            ("AddToCart", "AddToCart"),
                            ("InitiateCheckout", "InitiateCheckout"),
                            ("Purchase", "Purchase"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                (
                    "destination",
                    models.CharField(
                        choices=[
                            ("meta_capi", "Meta Conversions API"),
                            ("ga4", "GA4 Measurement Protocol"),
                        ],
                        db_index=True,
                        max_length=10,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        help_text="The frontend/order-derived id used to dedupe the browser pixel against this server-side send.",
                        max_length=100,
                    ),
                ),
                (
                    "is_manual_order",
                    models.BooleanField(
                        default=False,
                        help_text="Copied from the order at send time, so this stays meaningful even if the order changes later.",
                    ),
                ),
                ("request_payload", models.JSONField(blank=True, default=dict)),
                (
                    "response_status",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("response_body", models.JSONField(blank=True, default=dict)),
                ("success", models.BooleanField(db_index=True, default=False)),
                ("error_message", models.CharField(blank=True, max_length=500)),
                ("attempt", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracking_events",
                        to="orders.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["event_name", "destination", "-created_at"],
                        name="marketing_t_event_n_ebd607_idx",
                    )
                ],
            },
        ),
    ]
