# Generated by Django 5.2.17 on 2026-09-20 10:49

import apps.core.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_product_productattribute_attributevalue_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32, unique=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("flat", "Flat amount"), ("percentage", "Percentage")],
                        max_length=10,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Percentage coupons only: caps the discount in currency, e.g. 20% off up to ৳500.",
                        max_digits=12,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "min_order_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "start_at",
                    models.DateTimeField(
                        blank=True, help_text="Blank: usable immediately.", null=True
                    ),
                ),
                (
                    "expiry_at",
                    models.DateTimeField(
                        blank=True, help_text="Blank: never expires.", null=True
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "total_usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank: unlimited.", null=True
                    ),
                ),
                (
                    "per_customer_usage_limit",
                    models.PositiveIntegerField(
                        blank=True, help_text="Blank: unlimited.", null=True
                    ),
                ),
                ("exclude_sale_items", models.BooleanField(default=False)),
                ("first_order_only", models.BooleanField(default=False)),
                ("free_shipping", models.BooleanField(default=False)),
                (
                    "brands",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.brand"
                    ),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.category"
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="coupons", to="catalog.product"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "phone",
                    models.CharField(
                        max_length=11,
                        validators=[apps.core.validators.validate_bd_phone],
                    ),
                ),
                ("order_reference", models.CharField(blank=True, max_length=64)),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="usages",
                        to="coupons.coupon",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("type", "flat"),
                    models.Q(("type", "percentage"), ("amount__lte", 100)),
                    _connector="OR",
                ),
                name="coupon_percentage_amount_max_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("expiry_at__isnull", True),
                    ("start_at__isnull", True),
                    ("expiry_at__gt", models.F("start_at")),
                    _connector="OR",
                ),
                name="coupon_expiry_after_start",
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(
                fields=["coupon", "user"], name="coupons_cou_coupon__830da4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(
                fields=["coupon", "phone"], name="coupons_cou_coupon__d3780d_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.UniqueConstraint(
                condition=models.Q(("order_reference", ""), _negated=True),
                fields=("coupon", "order_reference"),
                name="couponusage_unique_order",
            ),
        ),
    ]
